FROM node:12-alpine AS builder
WORKDIR /app
COPY /client-app-v2/package.json ./

RUN npm config set @ravestudio:registry=https://npm.pkg.github.com
RUN npm config set //npm.pkg.github.com/:_authToken=""


RUN npm install

COPY /xplatform-controls/build ./node_modules/xplatform-controls/
COPY /xplatform-controls/package.json ./node_modules/xplatform-controls/

COPY /client-app-v2/. .

RUN npm run build

FROM arm32v7/nginx

COPY /nginx/client/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build /usr/share/nginx/html
