version: "3.4"

networks:
  dockerapi-dev:
    driver: bridge

services:
  clientapp:
    image: yakovlevdev/client-app:latest
    container_name: clientapp
    networks:
      - dockerapi-dev

  dockerapi:
    image: yakovlevdev/xplatform:latest
    container_name: api
    ports:
      - "8000:80"
    environment:
      xpl_db: "host=postgres_image;port=5432;database=xpl_db;username=xuser;password=xpss"
      logPath: "/logpath"
    volumes:
      - ./logs:/logpath
    networks:
      - dockerapi-dev

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "xuser"
      POSTGRES_PASSWORD: "xpss"
      POSTGRES_DB: "xpl_db"
    networks:
      - dockerapi-dev

volumes:
  db_volume:
