FROM node:20-alpine AS builder
WORKDIR /app
COPY /client-app-v2/package.json ./

RUN npm config set @ravestudio:registry=https://npm.pkg.github.com
RUN npm config set //npm.pkg.github.com/:_authToken=""


RUN npm install

COPY /xplatform-controls/build ./node_modules/xplatform-controls/
COPY /xplatform-controls/package.json ./node_modules/xplatform-controls/

COPY /client-app-v2/. .

RUN npm run build

FROM nginx:1.17-alpine

COPY /nginx/client/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist /usr/share/nginx/html
