FROM node:13.12.0-alpine AS builder
WORKDIR /app
COPY /client-app/package.json ./

RUN npm install

COPY /xplatform-controls/build ./node_modules/xplatform-controls/
COPY /xplatform-controls/package.json ./node_modules/xplatform-controls/

COPY /client-app/. .

RUN npm run build

FROM nginx:1.17-alpine

COPY --from=builder /app/build /usr/share/nginx/html