// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xplatform.DataAccess;

namespace xplatform.Migrations
{
    [DbContext(typeof(XContext))]
    [Migration("20190720152304_addInitdb")]
    partial class addInitdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("CommonLib.Objects.Emitent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.Property<string>("WebSite")
                        .HasColumnName("WebSite");

                    b.HasKey("Id");

                    b.ToTable("EmitentSet");
                });

            modelBuilder.Entity("CommonLib.Objects.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<decimal>("Amortization")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Capex")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnName("CurrentAssets")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnName("CurrentLiabilities")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DividendsPaid")
                        .HasColumnName("DividendsPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EarningsPerShare")
                        .HasColumnName("EarningsPerShare")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EmitentId");

                    b.Property<decimal>("FixedAssets")
                        .HasColumnName("FixedAssets")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FlowFinancingActivities")
                        .HasColumnName("FlowFinancingActivities")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FlowInvestingActivities")
                        .HasColumnName("FlowInvestingActivities")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FlowOperatingActivities")
                        .HasColumnName("FlowOperatingActivities")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IncomeTaxPaid")
                        .HasColumnName("IncomeTaxPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LongTermLiabilities")
                        .HasColumnName("LongTermLiabilities")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NWC")
                        .HasColumnName("NWC")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetIncome")
                        .HasColumnName("NetIncome")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OperatingIncome")
                        .HasColumnName("OperatingIncome")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Period")
                        .HasColumnName("Period");

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnName("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("StockIssuance")
                        .HasColumnName("StockIssuance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Year")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("EmitentId");

                    b.ToTable("FinancialSet");
                });

            modelBuilder.Entity("CommonLib.Objects.Financial", b =>
                {
                    b.HasOne("CommonLib.Objects.Emitent", "Emitent")
                        .WithMany("Financials")
                        .HasForeignKey("EmitentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
